### ISSUE TITLE
Banner Callout

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#198]
Functionality:

This callout can take a node and all fields can be overwritten in the BE.

<hr>
Reference:

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=755%3A1319)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/bd14f935-ac85-4ed9-a8af-f448d0174a0c)

**Comment by pingevt** [comment]
@morganfoust @yasmeenfahmy - This Screenshot has a button top-right and the Figma doesn't anymore... Is that an intentional loss?

@maxfenton - I'm thinking this is the :eft/Right Callout, minus orientation and media. And the date text here I think can be handled in the WYSIWYG, rather than a distinct field. Can we make these data structures the same?

**Comment by maxfenton** [comment]
I think we can handle a left/right callout that doesn't have media to look sortof like this, but I think this component is specifically a callout for an Event and needs to automatically get the Event information — title and description and dates and ticket links — but not let the client wysiwyg anything.

**Comment by pingevt** [comment]
Good points @maxfenton ,

@morganfoust @yasmeenfahmy - can we confirm what type of content can be in these callouts?

**Comment by morganfoust** [comment]
@pingevt I don't think that was an intentional loss of the CTA (I checked the last client deliverable and it contains a CTA, and I couldn't find anything to suggest to remove) - I've added it back in Figma. 

To my knowledge, this banner should be able to support any of the content types currently used in this block on the [homepage](https://longwoodgardens.org/): 

<img width="1009" alt="Screen Shot 2022-01-31 at 9 39 41 AM" src="https://user-images.githubusercontent.com/50842575/151813438-39c07f4f-ce6b-4742-8e58-6fa5478a7f90.png">

Definitely events, what's in bloom, and blog posts.

**Comment by pingevt** [comment]
1/31 - Can take a node, and have override fields. Any CT

**Comment by maxfenton** [comment]
<img width="1129" alt="Screen Shot 2022-02-22 at 9 06 14 AM" src="https://user-images.githubusercontent.com/906502/155148406-0929d74b-8233-435b-b1a6-b2eb5d797333.png">
